# permissions for end users to edit sendmessages.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: sendmessage-editor-role
rules:
- apiGroups:
  - sendmessage.sendmessage.io
  resources:
  - sendmessages
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - sendmessage.sendmessage.io
  resources:
  - sendmessages/status
  verbs:
  - get
